version: '3.8'

services:
  agentforce-server:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    # Uncomment the following lines if you need to connect to Ollama
    # networks:
    #   - agentforce-network

# Uncomment if you want to run Ollama alongside the server
# networks:
#   agentforce-network:
#     driver: bridge
